# Generated by Django 4.2.13 on 2024-06-06 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caosNewsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar',
            name='apellido',
            field=models.CharField(db_column='apellido', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='email',
            field=models.EmailField(db_column='email', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='nombre',
            field=models.CharField(db_column='nombre', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrar',
            name='password',
            field=models.CharField(db_column='password', max_length=20),
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(db_column='id_noticia', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='titulo', max_length=100)),
                ('cuerpo', models.CharField(db_column='cuerpo', max_length=500)),
                ('fecha', models.DateField(db_column='fecha')),
                ('ubicacion', models.CharField(db_column='ubicacion', max_length=50)),
                ('categoria', models.CharField(db_column='categoria', max_length=50)),
                ('imagen', models.BooleanField(db_column='imagen', null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='caosNewsApp.registrar')),
            ],
        ),
    ]
