# Generated by Django 4.2.13 on 2024-06-06 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caosNewsApp', '0002_alter_registrar_apellido_alter_registrar_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('categoria', models.CharField(db_column='categoria', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.ForeignKey(db_column='categoria', on_delete=django.db.models.deletion.CASCADE, to='caosNewsApp.categoria'),
        ),
    ]
