# Generated by Django 4.2.13 on 2024-06-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosNewsApp', '0003_categoria_alter_noticia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], db_column='estado', default=1),
        ),
        migrations.AddField(
            model_name='registrar',
            name='estado',
            field=models.IntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], db_column='estado', default=1),
        ),
    ]
