# Generated by Django 4.2.13 on 2024-06-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caosNewsApp', '0004_noticia_estado_registrar_estado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registrar',
            new_name='Usuarios',
        ),
    ]
