# Generated by Django 4.2.13 on 2024-06-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caosNewsApp', '0005_rename_registrar_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=models.TextField(db_column='cuerpo', max_length=500),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, db_column='imagen', null=True, upload_to='noticias/'),
        ),
    ]
